apiVersion: v2
name: activeloop-neohorizon
description: Activeloop NeoHorizon Deployment Chart
type: application
version: 0.2.2
appVersion: "v0.1.12"
kubeVersion: ">= 1.24.0-0"

maintainers:
  - name: Activeloop SRE
    email: sre@activeloop.dev

sources:
  - https://github.com/activeloopai/activeloop-helm-charts
home: https://activeloop.ai
icon: https://static.activeloop.io/logos/SVG/activeloop-logo-256x256.svg

keywords:
  - activeloop
  - neohorizon
  - deeplake

dependencies:
  - name: postgresql
    version: 16.7.16
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.create

  - name: rabbitmq
    version: 16.0.10
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: rabbitmq.create
