apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activeloop-neohorizon.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ include "chart.name" . }}
    helm.sh/chart: {{ .Chart.Name }}
type: Opaque
stringData:
  {{- with .Values.global.config }}
  {{- range $key, $value := . }}
  {{ $key | upper }}: {{ $value | trim | quote }}
  {{- end }}
  {{- end }}
  USE_DEEPLAKE: "true"
  USE_RABBITMQ: "true"
  USE_DEEPLAKE_AUTH: "false"
  ENVIRONMENT: "local"
  RABBITMQ_URL: {{ include "activeloop-neohorizon.rabbitmqConnection" . | trim | quote }}
  POSTGRES_DB: {{ default .Values.postgresql.auth.database .Values.global.config.postgres_db | trim | quote }}
  POSTGRES_HOST: {{ include "activeloop-neohorizon.postgresqlHost" . | trim | quote }}
  POSTGRES_PASSWORD: {{ default .Values.postgresql.auth.password .Values.global.config.postgres_password | trim | quote }}
  POSTGRES_PORT: {{ default .Values.postgresql.primary.service.ports.postgresql .Values.global.config.postgres_port | quote | trim }}
  POSTGRES_USER: {{ default .Values.postgresql.auth.username .Values.global.config.postgres_user | trim | quote }}
  {{- if .Values.models.visual_model }}
  TEXT_IMAGE__MATRIX_OF_EMBEDDINGS__INGESTION_URL: {{ default ( printf "http://%s-%s-svc.%s.svc.cluster.local/v2/models/%s/infer" (include "chart.name" $) "visual-model" .Release.Namespace .Values.models.visual_model.model_name ) .Values.global.config.text_image_matrix_of_embeddings_ingestion_url | trim | quote }}
  TEXT_IMAGE__MATRIX_OF_EMBEDDINGS__QUERY_URL: {{ default ( printf "http://%s-%s-svc.%s.svc.cluster.local/v2/models/%s/infer" (include "chart.name" $) "visual-model" .Release.Namespace .Values.models.visual_model.model_name ) .Values.global.config.text_image_matrix_of_embeddings_query_url | trim | quote }}
  TEXT_IMAGE__EMBEDDING__INGESTION_URL: {{ default ( printf "http://%s-%s-svc.%s.svc.cluster.local/v2/models/%s/infer" (include "chart.name" $) "visual-model" .Release.Namespace .Values.models.visual_model.model_name ) .Values.global.config.text_image_embedding_ingestion_url | trim | quote }}
  TEXT_IMAGE__EMBEDDING__QUERY_URL: {{ default ( printf "http://%s-%s-svc.%s.svc.cluster.local/v2/models/%s/infer" (include "chart.name" $) "visual-model" .Release.Namespace .Values.models.visual_model.model_name ) .Values.global.config.text_image_embedding_query_url | trim | quote }}
  {{- end }}
  {{- if .Values.models.text_model }}
  TEXT__EMBEDDING__INGESTION_URL: {{ default ( printf "http://%s-%s-svc.%s.svc.cluster.local/v2/models/%s/infer" (include "chart.name" $) "text-model" .Release.Namespace .Values.models.text_model.model_name ) .Values.global.config.text__embedding__ingestion_url | trim | quote }}
  TEXT__EMBEDDING__QUERY_URL: {{ default ( printf "http://%s-%s-svc.%s.svc.cluster.local/v2/models/%s/infer" (include "chart.name" $) "text-model" .Release.Namespace .Values.models.text_model.model_name ) .Values.global.config.text__embedding__query_url | trim | quote }}
  {{- end }}
