{{- if not .Values.global.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activeloop-neohorizon.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ include "chart.name" . }}
    helm.sh/chart: {{ .Chart.Name }}
type: Opaque
stringData:
  USE_RABBITMQ: "true"
  USE_DEEPLAKE: "true"
  USE_DEEPLAKE_AUTH: "false"
  ENVIRONMENT: "local"
  EMBEDDING_PROVIDER_TYPE: "TRITON"
  CORS_ALLOW_ORIGINS:  "*"
  OPENAI_API_KEY: {{ .Values.global.config.openai_api_key | trim | quote }}
  GEMINI_API_KEY: {{ .Values.global.config.gemini_api_key | trim | quote }}
  DEEPLAKE_ROOT_DIR: {{ required "global.config.deeplake_root_dir is required" .Values.global.config.deeplake_root_dir | trim | quote }}
  AL_API_TOKEN: {{ required "global.config.al_api_token is required" .Values.global.config.al_api_token | trim | quote }}
  RABBITMQ_URL: {{ include "activeloop-neohorizon.rabbitmqConnection" . | trim | quote }}
  POSTGRES_DB: {{ default .Values.postgresql.auth.database .Values.global.config.postgres_db | trim | quote }}
  POSTGRES_HOST: {{ include "activeloop-neohorizon.postgresqlHost" . | trim | quote }}
  POSTGRES_PASSWORD: {{ default .Values.postgresql.auth.password .Values.global.config.postgres_password | trim | quote }}
  POSTGRES_PORT: {{ default .Values.postgresql.primary.service.ports.postgresql .Values.global.config.postgres_port | quote | trim }}
  POSTGRES_USER: {{ default .Values.postgresql.auth.username .Values.global.config.postgres_user | trim | quote }}
  TEXT_IMAGE__MATRIX_OF_EMBEDDINGS__INGESTION_URL: {{ default "" .Values.global.config.text_image__matrix_of_embeddings__ingestion_url | quote }}
  TEXT_IMAGE__MATRIX_OF_EMBEDDINGS__QUERY_URL: {{ default "" .Values.global.config.text_image__matrix_of_embeddings__query_url | quote }}
  TEXT_IMAGE__EMBEDDING__INGESTION_URL: {{ default "" .Values.global.config.text_image__embedding__ingestion_url | quote }}
  TEXT_IMAGE__EMBEDDING__QUERY_URL: {{ default "" .Values.global.config.text_image__embedding__query_url | quote }}
  TEXT__EMBEDDING__INGESTION_URL: {{ default "" .Values.global.config.text__embedding__ingestion_url | quote }}
  TEXT__EMBEDDING__QUERY_URL: {{ default "" .Values.global.config.text__embedding__query_url | quote }}
  TEXT__SUMMARY_EMBEDDING__QUERY_URL: {{ default "" .Values.global.text__summary_embedding__query_url | quote }}
  TEXT__SUMMARY_EMBEDDING__INGESTION_URL: {{ default "" .Values.global.text__summary_embedding__ingestion_url | quote }}
  {{ with .Values.global.config.deeplake_creds }}
  DEEPLAKE_CREDS: {{ . | trim | quote }}
  {{ end }}
{{- end }}
