{{- with .Values.models }}
{{- range . }}
{{- if and (not (empty .load_models)) .ingress.enabled }}
{{ $sp := default 80 .service.port }}
{{ $name := printf "%s-%s" (include "chart.name" $) .name | kebabcase }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $.Release.Name }}
    app.kubernetes.io/component: models
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ include "chart.name" $ }}
    helm.sh/chart: {{ $.Chart.Name }}
    {{- with .ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}

  rules:
    - host: {{ .ingress.host }}
      http:
        paths:
          {{- range .ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $sp }}
          {{- end }}
  {{- if .ingress.tls }}
  tls:
    {{- toYaml .ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{/*
*/}}
