{{- with .Values.models }}
{{- range . }}
{{- if .load_models }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s-svc" (include "chart.name" $) .name | kebabcase }}
  labels:
    app.kubernetes.io/name: {{ .name | kebabcase }}
    app.kubernetes.io/component: models
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ include "chart.name" $ }}
    helm.sh/chart: {{ $.Chart.Name }}
    {{- with .service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  type: {{ default "ClusterIP" .service.type }}

  {{- with .service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}

  {{- with .service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}

  {{- with .service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if and (eq .service.type "LoadBalancer") .service.loadBalancerClass }}
  loadBalancerClass: {{ .service.loadBalancerClass | quote }}
  {{- end }}

  ports:
    - name: http
      port: {{ .service.port | default 80 }}
      targetPort: {{ .port | default 8000 }}
      protocol: TCP
    {{- if .service.nodePort }}
      nodePort: {{ .service.nodePort }}
    {{- end }}
    {{- with .service.additionalPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ .name | kebabcase }}
    app.kubernetes.io/component: models
    app.kubernetes.io/instance: {{ $.Release.Name }}
  {{- with .service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
