x-environment: &environment
  USE_RABBITMQ: "true"
  USE_DEEPLAKE: "true"
  ENVIRONMENT: "local"
  POSTGRES_DATABASE: "${POSTGRES_DATABASE:-neohorizon}"
  POSTGRES_HOST: "${POSTGRES_HOST:-al-neohorizon-postgres}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
  POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
  POSTGRES_USER: "${POSTGRES_USER:-postgres}"
  RABBITMQ_URL: "${RABBITMQ_URL:-amqp://neohorizon:neohorizon@al-neohorizon-rabbitmq:5672}"
  DEEPLAKE_ROOT_DIR: "${DEEPLAKE_ROOT_DIR:-/var/lib/deeplake}"
  AL_API_TOKEN: "${AL_API_TOKEN:?}"
  GEMINI_API_KEY: "${GEMINI_API_KEY}"
  OPENAI_API_KEY: "${OPENAI_API_KEY}"
  TEXT_IMAGE__MATRIX_OF_EMBEDDINGS__INGESTION_URL: "${TEXT_IMAGE__MATRIX_OF_EMBEDDINGS__INGESTION_URL:-http://al-neohorizon-model:8000/v2/models/${AL_MODEL_NAME:?}/infer}"
  TEXT_IMAGE__MATRIX_OF_EMBEDDINGS__QUERY_URL: "${TEXT_IMAGE__MATRIX_OF_EMBEDDINGS__QUERY_URL:-http://al-neohorizon-model:8000/v2/models/${AL_MODEL_NAME:?}/infer}"
  TEXT_IMAGE__EMBEDDING__INGESTION_URL: "${TEXT_IMAGE__EMBEDDING__INGESTION_URL:-http://al-neohorizon-model:8000/v2/models/${AL_MODEL_NAME:?}/infer}"
  TEXT_IMAGE__EMBEDDING__QUERY_URL: "${TEXT_IMAGE__EMBEDDING__QUERY_URL:-http://al-neohorizon-model:8000/v2/models/${AL_MODEL_NAME:?}/infer}"
  TEXT__EMBEDDING__INGESTION_URL: "${TEXT__EMBEDDING__INGESTION_URL:-http://al-neohorizon-model:8000/v2/models/${AL_MODEL_NAME:?}/infer}"
  TEXT__EMBEDDING__QUERY_URL: "${TEXT__EMBEDDING__QUERY_URL:-http://al-neohorizon-model:8000/v2/models/${AL_MODEL_NAME:?}/infer}"
  # DEEPLAKE_CREDS: "${DEEPLAKE_CREDS}"
  # Uncomment this if you want to use google application credentials
  # GOOGLE_APPLICATION_CREDENTIALS: "/creds/google-application-credentials.json"

x-shared-apps: &shared-apps
  restart: always
  depends_on:
    - change_vol_ownership
  networks:
    - al-neohorizon-network
  volumes:
    - al_neohorizon_deeplake_data:/var/lib/deeplake
  # Uncomment this if you want to use google application credentials
  # configs:
  #   - source: google-application-credentials
  #     target: /creds/google-application-credentials.json

x-shared-deps: &shared-deps
  restart: always
  networks:
    - al-neohorizon-network

services:
  change_vol_ownership:
    container_name: al-neohorizon-change-vol-ownership
    image: busybox
    command: chown -R 10001:10001 /var/lib/deeplake
    restart: "no"
    volumes:
      - al_neohorizon_deeplake_data:/var/lib/deeplake
  main-api:
    container_name: al-neohorizon-main-api
    image: quay.io/activeloopai/neohorizon-main:${AL_IMAGE_TAG:-latest}
    entrypoint:
      - python3
      - lightweight_service.py
    environment:
      PORT: 8000
      <<: *environment
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    <<: *shared-apps
  files-api:
    container_name: al-neohorizon-files-api
    image: quay.io/activeloopai/neohorizon-files:${AL_IMAGE_TAG:-latest}
    entrypoint:
      - python3
      - files_service.py
    environment:
      PORT: 8000
      <<: *environment
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    <<: *shared-apps
  vector_search_worker:
    container_name: al-neohorizon-vector-search-worker
    image: quay.io/activeloopai/neohorizon-main:${AL_IMAGE_TAG:-latest}
    entrypoint:
      - python3
      - vector_search_worker.py
    environment:
      <<: *environment
    <<: *shared-apps
  file_processor_worker:
    container_name: al-neohorizon-file-processor-worker
    image: quay.io/activeloopai/neohorizon-main:${AL_IMAGE_TAG:-latest}
    entrypoint:
      - python3
      - file_processor_worker.py
    environment:
      <<: *environment
    <<: *shared-apps
  embedding_worker:
    container_name: al-neohorizon-embedding-worker
    image: quay.io/activeloopai/neohorizon-main:${AL_IMAGE_TAG:-latest}
    entrypoint:
      - python3
      - embedding_worker.py
    environment:
      <<: *environment
    <<: *shared-apps
  summary_generation_worker:
    container_name: al-neohorizon-summary-generation-worker
    image: quay.io/activeloopai/neohorizon-main:${AL_IMAGE_TAG:-latest}
    entrypoint:
      - python3
      - summary_generation_worker.py
    environment:
      <<: *environment
    <<: *shared-apps
  model:
    container_name: al-neohorizon-model
    image: quay.io/activeloopai/models-triton:${AL_IMAGE_TAG_MODEL:-latest}
    <<: *shared-deps
    runtime: nvidia
    shm_size: ${SHM_SIZE:-8g}
    command:
      - --load-model=${AL_MODEL_NAME:?}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["0"]
            capabilities: [gpu]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: al-neohorizon-rabbitmq
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    volumes:
      - al_neohorizon_rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=neohorizon
      - RABBITMQ_DEFAULT_PASS=neohorizon
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    <<: *shared-deps

  postgres:
    image: postgres:17
    container_name: al-neohorizon-postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - al_neohorizon_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=neohorizon
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    <<: *shared-deps

  proxy:
    container_name: al-neohorizon-proxy
    image: nginx:latest
    depends_on:
      - main-api
      - files-api
    ports:
      - "${LISTEN_HOST:-0.0.0.0}:${LISTEN_PORT:-80}:80"
    configs:
      - source: al-proxy-config
        target: /etc/nginx/conf.d/default.conf
    <<: *shared-deps

networks:
  al-neohorizon-network:
    driver: bridge

volumes:
  al_neohorizon_rabbitmq_data:
    driver: local
  al_neohorizon_postgres_data:
    driver: local
  al_neohorizon_deeplake_data:
    driver: local

configs:
  # Uncomment this if you want to use google application credentials
  # google-application-credentials:
  #   content: |
  #     JSON_CONTENT_HERE
  al-proxy-config:
    content: |
      server {
        client_max_body_size 512m;
        listen 80;
        server_name _;

        location /files {
          proxy_pass http://al-neohorizon-files-api:8000;
        }

        location / {
          proxy_pass http://al-neohorizon-main-api:8000;
        }
      }
